# Generated by Django 2.1 on 2020-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200715_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
